language: node_js
node_js:
  - "6.6"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7
      - pkg-config 
      - libncurses5-dev 
      - libssl-dev 
      - libnss3-dev 
      - libexpat-dev

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-4.7";
      export CXX="g++-4.7";
      export LINK="gcc-4.7";
      export LINKXX="g++-4.7";
    fi
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version
  - python -V

before_script:
  - npm install -g truffle 
  - npm install -g ethereumjs-testrpc
  - nohup testrpc &
